name: ci
permissions:
  contents: read

on:
  push:
    branches:
     - master
     - next*

  pull_request:
    branches:
     - master
     - next*

jobs:
  ci-without-nix:
    name: CCM Integration tests
    uses: ./.github/workflows/integration-tests.yml
    with:
      # use a fixed release (not unstable/master), since master builds are cleared from S3 once in a while
      # bump it to the latest scylla release from time to time
      scylla_version: "release:2026.3.1"
  ci-with-nix:
    name: CCM Integration tests (using Nix)
    uses: ./.github/workflows/nix.yml
    with:
      # use a fixed release (not unstable/master), since master builds are cleared from S3 once in a while
      # bump it to the latest scylla release from time to time
      scylla_version: "release:2026.3.1"
  ci-docker:
    name: Docker/Podman Integration tests
    uses: ./.github/workflows/docker-tests.yml
