name: CCM Integration tests

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      reloc_version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - name: Install uv
      uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Setup java
      uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Install dependencies
      run: |
        uv sync

    - name: Cache binary versions
      id: cache-versions
      uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
      with:
        path: |
          ~/.ccm/repository
          ~/.ccm/scylla-repository
        key: ${{ runner.os }}-${{ inputs.reloc_version }}-binaries

    - name: Set environmental variables
      run: |
        echo "SCYLLA_VERSION=unstable/master:${{ inputs.reloc_version }}" >> "$GITHUB_ENV"

    - name: Download versions
      if: steps.cache-versions.outputs.cache-hit != 'true'
      run: |
        normalized=$(echo ${{ inputs.reloc_version }} | tr ':' '_')
        if [ ! -f ~/.ccm/scylla-repository/unstable/master/$normalized ]; then
          uv run ./ccm create temp -n 1 --scylla --version unstable/master:${{ inputs.reloc_version }}
          uv run ./ccm remove
        fi
        uv run ./ccm create temp-cas -n 1 --version 3.11.4 > /dev/null
        uv run ./ccm remove

    - name: Test with pytest
      run: |
        uv run python -m pytest ./tests -x

    - name: Copy logs/results
      if: contains(github.event.pull_request.labels.*.name, 'PR-upload-log')
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: ccm-tests-log
        path: tests/test_results/
